local addonName, ns = ...

-- Auto-generated split from fr0z3nUI_QuestTracker_DB2.lua on 20260121_173032
-- Expansion DB00 (Unknown/Unclassified)

ns.rules = ns.rules or {}

local EXPANSION_ID = 0
local EXPANSION_NAME = "Unclassified"

local Y, N = true, false

-- Currency gates (optional):
--   item.currencyID = { currencyID, required }
-- Amount sources (Retail):
--   Character amount: C_CurrencyInfo.GetCurrencyInfo(id).quantity
--   Warband total: C_CurrencyInfo.GetAccountCharacterCurrencyData(id)
--     (requires RequestCurrencyDataForAccountCharacters() to be called earlier)
--   Transferability: C_CurrencyInfo.GetCurrencyInfo(id).isAccountTransferable
-- Notes:
--   If isAccountTransferable is true, the tracker gates using the warband total (falls back to a cached
--   account saved-variable snapshot if the live data isn't available yet).
-- Placeholders usable in itemInfo/textInfo/spellInfo:
--   {currency:name} {currency:req} {currency:char} {currency:wb} {currency} (gate amount)
-- Shorthand (DB convenience):
--   %p  -> {progress}
--   $rq -> {currency:req}
--   $nm -> {currency:name}
--   $hv -> {currency} (gate/have amount)
--   $ga -> {currency} (gate/have amount)
--   $cc -> {currency:char}
--   $wb -> {currency:wb}


-- item.required tuple keys:
--   item.required = { count, hideWhenAcquired, autoBuyEnabled, autoBuyMax }
local REQ_COUNT, REQ_HIDE, REQ_BUY_ON, REQ_BUY_MAX = 1, 2, 3, 4
local bakedRules = {

--  12   MIDNIGHT PROFESSIONS         If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Midnight Alchemy",        frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2906, locationID = 2393, textInfo = "Midnight Alchemy\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2906 }, key = "XP12:Prof:Alchemy",        },
  {label = "Midnight Blacksmithing",  frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2907, locationID = 2393, textInfo = "Midnight Blacksmithing\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2907 }, key = "XP12:Prof:Blacksmithing", },
  {label = "Midnight Cooking",        frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2908, locationID = 2393, textInfo = "Midnight Cooking\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2908 }, key = "XP12:Prof:Cooking",        },
  {label = "Midnight Enchanting",     frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2909, locationID = 2393, textInfo = "Midnight Enchanting\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2909 }, key = "XP12:Prof:Enchanting",     },
  {label = "Midnight Engineering",    frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2910, locationID = 2393, textInfo = "Midnight Engineering\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2910 }, key = "XP12:Prof:Engineering",    },
  {label = "Midnight Fishing",        frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2911, locationID = 2393, textInfo = "Midnight Fishing\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2911 }, key = "XP12:Prof:Fishing",        },
  {label = "Midnight Herbalism",      frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2912, locationID = 2393, textInfo = "Midnight Herbalism\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2912 }, key = "XP12:Prof:Herbalism",      },
  {label = "Midnight Inscription",    frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2913, locationID = 2393, textInfo = "Midnight Inscription\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2913 }, key = "XP12:Prof:Inscription",    },
  {label = "Midnight Jewelcrafting",  frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2914, locationID = 2393, textInfo = "Midnight Jewelcrafting\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2914 }, key = "XP12:Prof:Jewelcrafting",  },
  {label = "Midnight Leatherworking", frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2915, locationID = 2393, textInfo = "Midnight Leatherworking\n - Open Profession After",     hideWhenCompleted = true, complete = { skillLineID = 2915 }, key = "XP12:Prof:Leatherworking", },
  {label = "Midnight Mining",         frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2916, locationID = 2393, textInfo = "Midnight Mining\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2916 }, key = "XP12:Prof:Mining",         },
  {label = "Midnight Skinning",       frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2917, locationID = 2393, textInfo = "Midnight Skinning\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2917 }, key = "XP12:Prof:Skinning",       },
  {label = "Midnight Tailoring",      frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2918, locationID = 2393, textInfo = "Midnight Tailoring\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2918 }, key = "XP12:Prof:Tailoring",      },

--  11   KHAZ ALGAR PROFESSIONS       If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Khaz Alchemy",            frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2871, locationID = 6666666, textInfo = "Khaz Alchemy\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2871 }, key = "XP11:Prof:Alchemy", },
  {label = "Khaz Blacksmithing",      frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2872, locationID = 6666666, textInfo = "Khaz Blacksmithing\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2872 }, key = "XP11:Prof:Blacksmithing", },
  {label = "Khaz Cooking",            frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2873, locationID = 6666666, textInfo = "Khaz Cooking\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2873 }, key = "XP11:Prof:Cooking", },
  {label = "Khaz Enchanting",         frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2874, locationID = 6666666, textInfo = "Khaz Enchanting\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2874 }, key = "XP11:Prof:Enchanting", },
  {label = "Khaz Engineering",        frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2875, locationID = 6666666, textInfo = "Khaz Engineering\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2875 }, key = "XP11:Prof:Engineering", },
  {label = "Khaz Fishing",            frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2876, locationID = 6666666, textInfo = "Khaz Fishing\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2876 }, key = "XP11:Prof:Fishing", },
  {label = "Khaz Herbalism",          frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2877, locationID = 6666666, textInfo = "Khaz Herbalism\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2877 }, key = "XP11:Prof:Herbalism", },
  {label = "Khaz Inscription",        frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2878, locationID = 6666666, textInfo = "Khaz Inscription\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2878 }, key = "XP11:Prof:Inscription", },
  {label = "Khaz Jewelcrafting",      frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2879, locationID = 6666666, textInfo = "Khaz Jewelcrafting\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2879 }, key = "XP11:Prof:Jewelcrafting", },
  {label = "Khaz Leatherworking",     frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2880, locationID = 6666666, textInfo = "Khaz Leatherworking\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2880 }, key = "XP11:Prof:Leatherworking", },
  {label = "Khaz Mining",             frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2881, locationID = 6666666, textInfo = "Khaz Mining\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2881 }, key = "XP11:Prof:Mining", },
  {label = "Khaz Skinning",           frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2882, locationID = 6666666, textInfo = "Khaz Skinning\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2882 }, key = "XP11:Prof:Skinning", },
  {label = "Khaz Tailoring",          frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2883, locationID = 6666666, textInfo = "Khaz Tailoring\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2883 }, key = "XP11:Prof:Tailoring", },

--  10   DRAGONFLIGHT PROFESSIONS     If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Dragon Alchemy",          frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2823, locationID = 1978, textInfo = "Dragon Alchemy\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2823 }, key = "XP10:Prof:Alchemy", },
  {label = "Dragon Blacksmithing",    frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2822, locationID = 1978, textInfo = "Dragon Blacksmithing\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2822 }, key = "XP10:Prof:Blacksmithing", },
  {label = "Dragon Cooking",          frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2824, locationID = 1978, textInfo = "Dragon Cooking\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2824 }, key = "XP10:Prof:Cooking", },
  {label = "Dragon Enchanting",       frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2825, locationID = 1978, textInfo = "Dragon Enchanting\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2825 }, key = "XP10:Prof:Enchanting", },
  {label = "Dragon Engineering",      frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2827, locationID = 1978, textInfo = "Dragon Engineering\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2827 }, key = "XP10:Prof:Engineering", },
  {label = "Dragon Fishing",          frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2826, locationID = 1978, textInfo = "Dragon Fishing\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2826 }, key = "XP10:Prof:Fishing", },
  {label = "Dragon Herbalism",        frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2832, locationID = 1978, textInfo = "Dragon Herbalism\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2832 }, key = "XP10:Prof:Herbalism", },
  {label = "Dragon Inscription",      frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2828, locationID = 1978, textInfo = "Dragon Inscription\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2828 }, key = "XP10:Prof:Inscription", },
  {label = "Dragon Jewelcrafting",    frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2829, locationID = 1978, textInfo = "Dragon Jewelcrafting\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2829 }, key = "XP10:Prof:Jewelcrafting", },
  {label = "Dragon Leatherworking",   frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2830, locationID = 1978, textInfo = "Dragon Leatherworking\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2830 }, key = "XP10:Prof:Leatherworking", },
  {label = "Dragon Mining",           frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2833, locationID = 1978, textInfo = "Dragon Mining\n - Open Profession After",               hideWhenCompleted = true, complete = { skillLineID = 2833 }, key = "XP10:Prof:Mining", },
  {label = "Dragon Skinning",         frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2834, locationID = 1978, textInfo = "Dragon Skinning\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2834 }, key = "XP10:Prof:Skinning", },
  {label = "Dragon Tailoring",        frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2831, locationID = 1978, textInfo = "Dragon Tailoring\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2831 }, key = "XP10:Prof:Tailoring", },

--  09   SHADOWLANDS PROFESSIONS      If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Shadow Alchemy",          frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2750, locationID = 1670, textInfo = "Shadow Alchemy\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2750 }, key = "XP09:Prof:Alchemy", },
  {label = "Shadow Blacksmithing",    frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2751, locationID = 1670, textInfo = "Shadow Blacksmithing\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2751 }, key = "XP09:Prof:Blacksmithing", },
  {label = "Shadow Cooking",          frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2752, locationID = 1670, textInfo = "Shadow Cooking\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2752 }, key = "XP09:Prof:Cooking", },
  {label = "Shadow Enchanting",       frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2753, locationID = 1670, textInfo = "Shadow Enchanting\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2753 }, key = "XP09:Prof:Enchanting", },
  {label = "Shadow Engineering",      frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2755, locationID = 1670, textInfo = "Shadow Engineering\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2755 }, key = "XP09:Prof:Engineering", },
  {label = "Shadow Fishing",          frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2754, locationID = 1670, textInfo = "Shadow Fishing\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2754 }, key = "XP09:Prof:Fishing", },
  {label = "Shadow Fishing Rod",      frameID = "list1", item = { itemID = 180136, required = { 1, true, N, 0 }, },        locationID = 1670, textInfo = " - Buy The Brokers Angle'r",                            key = "XP09:Prof:FishingRod", },
  {label = "Shadow Herbalism",        frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2760, locationID = 1670, textInfo = "Shadow Herbalism\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2760 }, key = "XP09:Prof:Herbalism", },
  {label = "Shadow Inscription",      frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2756, locationID = 1670, textInfo = "Shadow Inscription\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2756 }, key = "XP09:Prof:Inscription", },
  {label = "Shadow Jewelcrafting",    frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2757, locationID = 1670, textInfo = "Shadow Jewelcrafting\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2757 }, key = "XP09:Prof:Jewelcrafting", },
  {label = "Shadow Leatherworking",   frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2758, locationID = 1670, textInfo = "Shadow Leatherworking\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2758 }, key = "XP09:Prof:Leatherworking", },
  {label = "Shadow Mining",           frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2761, locationID = 1670, textInfo = "Shadow Mining\n - Open Profession After",               hideWhenCompleted = true, complete = { skillLineID = 2761 }, key = "XP09:Prof:Mining", },
  {label = "Shadow Skinning",         frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2762, locationID = 1670, textInfo = "Shadow Skinning\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2762 }, key = "XP09:Prof:Skinning", },
  {label = "Shadow Tailoring",        frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2759, locationID = 1670, textInfo = "Shadow Tailoring\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2759 }, key = "XP09:Prof:Tailoring", },

--  08   BATTLE PROFESSIONS           If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Battle Archaeology",      frameID = "list1",                              missingProfessionSkillLineID = 794,  locationID = 1163, textInfo = "Battle Archaeology\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 794 }, key = "XP08:Prof:Archaeology", },
  {label = "Battle Alchemy",          frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2478, locationID = 1163, textInfo = "Battle Alchemy\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2478 }, key = "XP08:Prof:Alchemy", },
  {label = "Battle Blacksmithing",    frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2437, locationID = 1163, textInfo = "Battle Blacksmithing\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2437 }, key = "XP08:Prof:Blacksmithing", },
  {label = "Battle Cooking",          frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2541, locationID = 1163, textInfo = "Battle Cooking\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2541 }, key = "XP08:Prof:Cooking", },
  {label = "Battle Enchanting",       frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2486, locationID = 1163, textInfo = "Battle Enchanting\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2486 }, key = "XP08:Prof:Enchanting", },
  {label = "Battle Engineering",      frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2499, locationID = 1163, textInfo = "Battle Engineering\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2499 }, key = "XP08:Prof:Engineering", },
  {label = "Battle Fishing",          frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2585, locationID = 1163, textInfo = "Battle Fishing\n - Open Profession After",              hideWhenCompleted = true, complete = { skillLineID = 2585 }, key = "XP08:Prof:Fishing", },
  {label = "Battle Herbalism",        frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2549, locationID = 1163, textInfo = "Battle Herbalism\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2549 }, key = "XP08:Prof:Herbalism", },
  {label = "Battle Inscription",      frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2508, locationID = 1163, textInfo = "Battle Inscription\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2508 }, key = "XP08:Prof:Inscription", },
  {label = "Battle Jewelcrafting",    frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2518, locationID = 1163, textInfo = "Battle Jewelcrafting\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2518 }, key = "XP08:Prof:Jewelcrafting", },
  {label = "Battle Leatherworking",   frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2525, locationID = 1163, textInfo = "Battle Leatherworking\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2525 }, key = "XP08:Prof:Leatherworking", },
  {label = "Battle Mining",           frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2565, locationID = 1163, textInfo = "Battle Mining\n - Open Profession After",               hideWhenCompleted = true, complete = { skillLineID = 2565 }, key = "XP08:Prof:Mining", },
  {label = "Battle Skinning",         frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2557, locationID = 1163, textInfo = "Battle Skinning\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2557 }, key = "XP08:Prof:Skinning", },
  {label = "Battle Tailoring",        frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2533, locationID = 1163, textInfo = "Battle Tailoring\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2533 }, key = "XP08:Prof:Tailoring", },

--  07  LEGION PROFESSIONS            If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Legion Alchemy",          frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2479, locationID = 6666666, textInfo = "Legion Alchemy\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2479 }, key = "XP07:Prof:Alchemy", },
  {label = "Legion Blacksmithing",    frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2454, locationID = 6666666, textInfo = "Legion Blacksmithing\n - Open Profession After",     hideWhenCompleted = true, complete = { skillLineID = 2454 }, key = "XP07:Prof:Blacksmithing", },
  {label = "Legion Cooking",          frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2542, locationID = 6666666, textInfo = "Legion Cooking\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2542 }, key = "XP07:Prof:Cooking", },
  {label = "Legion Enchanting",       frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2487, locationID = 6666666, textInfo = "Legion Enchanting\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2487 }, key = "XP07:Prof:Enchanting", },
  {label = "Legion Engineering",      frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2500, locationID = 6666666, textInfo = "Legion Engineering\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2500 }, key = "XP07:Prof:Engineering", },
  {label = "Legion Fishing",          frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2586, locationID = 6666666, textInfo = "Legion Fishing\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2586 }, key = "XP07:Prof:Fishing", },
  {label = "Legion Herbalism",        frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2550, locationID = 6666666, textInfo = "Legion Herbalism\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2550 }, key = "XP07:Prof:Herbalism", },
  {label = "Legion Inscription",      frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2508, locationID = 6666666, textInfo = "Legion Inscription\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2508 }, key = "XP07:Prof:Inscription", },
  {label = "Legion Jewelcrafting",    frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2518, locationID = 6666666, textInfo = "Legion Jewelcrafting\n - Open Profession After",     hideWhenCompleted = true, complete = { skillLineID = 2518 }, key = "XP07:Prof:Jewelcrafting", },
  {label = "Legion Leatherworking",   frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2526, locationID = 6666666, textInfo = "Legion Leatherworking\n - Open Profession After",    hideWhenCompleted = true, complete = { skillLineID = 2526 }, key = "XP07:Prof:Leatherworking", },
  {label = "Legion Mining",           frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2566, locationID = 6666666, textInfo = "Legion Mining\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2566 }, key = "XP07:Prof:Mining", },
  {label = "Legion Skinning",         frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2558, locationID = 6666666, textInfo = "Legion Skinning\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2558 }, key = "XP07:Prof:Skinning", },
  {label = "Legion Tailoring",        frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2534, locationID = 6666666, textInfo = "Legion Tailoring\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2534 }, key = "XP07:Prof:Tailoring", },

--  06  WARLORDS PROFESSIONS          If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Draenor Alchemy",         frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2480, locationID = 6666666, textInfo = "Draenor Alchemy\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2480 }, key = "XP06:Prof:Alchemy", },
  {label = "Draenor Blacksmithing",   frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2472, locationID = 6666666, textInfo = "Draenor Blacksmithing\n - Open Profession After",    hideWhenCompleted = true, complete = { skillLineID = 2472 }, key = "XP06:Prof:Blacksmithing", },
  {label = "Draenor Cooking",         frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2543, locationID = 6666666, textInfo = "Draenor Cooking\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2543 }, key = "XP06:Prof:Cooking", },
  {label = "Draenor Enchanting",      frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2488, locationID = 6666666, textInfo = "Draenor Enchanting\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2488 }, key = "XP06:Prof:Enchanting", },
  {label = "Draenor Engineering",     frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2501, locationID = 6666666, textInfo = "Draenor Engineering\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2501 }, key = "XP06:Prof:Engineering", },
  {label = "Draenor Fishing",         frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2587, locationID = 6666666, textInfo = "Draenor Fishing\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2587 }, key = "XP06:Prof:Fishing", },
  {label = "Draenor Herbalism",       frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2551, locationID = 6666666, textInfo = "Draenor Herbalism\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2551 }, key = "XP06:Prof:Herbalism", },
  {label = "Draenor Inscription",     frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2509, locationID = 6666666, textInfo = "Draenor Inscription\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2509 }, key = "XP06:Prof:Inscription", },
  {label = "Draenor Jewelcrafting",   frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2519, locationID = 6666666, textInfo = "Draenor Jewelcrafting\n - Open Profession After",    hideWhenCompleted = true, complete = { skillLineID = 2519 }, key = "XP06:Prof:Jewelcrafting", },
  {label = "Draenor Leatherworking",  frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2527, locationID = 6666666, textInfo = "Draenor Leatherworking\n - Open Profession After",   hideWhenCompleted = true, complete = { skillLineID = 2527 }, key = "XP06:Prof:Leatherworking", },
  {label = "Draenor Mining",          frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2567, locationID = 6666666, textInfo = "Draenor Mining\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2567 }, key = "XP06:Prof:Mining", },
  {label = "Draenor Skinning",        frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2559, locationID = 6666666, textInfo = "Draenor Skinning\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2559 }, key = "XP06:Prof:Skinning", },
  {label = "Draenor Tailoring",       frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2535, locationID = 6666666, textInfo = "Draenor Tailoring\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2535 }, key = "XP06:Prof:Tailoring", },

--  05  PANDARIA PROFESSIONS          If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Mists Alchemy",           frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2481, locationID = 6666666, textInfo = "Mists Alchemy\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2481 }, key = "XP05:Prof:Alchemy", },
  {label = "Mists Blacksmithing",     frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2473, locationID = 6666666, textInfo = "Mists Blacksmithing\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2473 }, key = "XP05:Prof:Blacksmithing", },
  {label = "Mists Cooking",           frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2544, locationID = 6666666, textInfo = "Mists Cooking\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2544 }, key = "XP05:Prof:Cooking", },
  {label = "Mists Enchanting",        frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2489, locationID = 6666666, textInfo = "Mists Enchanting\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2489 }, key = "XP05:Prof:Enchanting", },
  {label = "Mists Engineering",       frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2502, locationID = 6666666, textInfo = "Mists Engineering\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2502 }, key = "XP05:Prof:Engineering", },
  {label = "Mists Fishing",           frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2588, locationID = 6666666, textInfo = "Mists Fishing\n - Open Profession After",            hideWhenCompleted = true, complete = { skillLineID = 2588 }, key = "XP05:Prof:Fishing", },
  {label = "Mists Herbalism",         frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2552, locationID = 6666666, textInfo = "Mists Herbalism\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2552 }, key = "XP05:Prof:Herbalism", },
  {label = "Mists Inscription",       frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2510, locationID = 6666666, textInfo = "Mists Inscription\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2510 }, key = "XP05:Prof:Inscription", },
  {label = "Mists Jewelcrafting",     frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2520, locationID = 6666666, textInfo = "Mists Jewelcrafting\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2520 }, key = "XP05:Prof:Jewelcrafting", },
  {label = "Mists Leatherworking",    frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2528, locationID = 6666666, textInfo = "Mists Leatherworking\n - Open Profession After",     hideWhenCompleted = true, complete = { skillLineID = 2528 }, key = "XP05:Prof:Leatherworking", },
  {label = "Mists Mining",            frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2568, locationID = 6666666, textInfo = "Mists Mining\n - Open Profession After",             hideWhenCompleted = true, complete = { skillLineID = 2568 }, key = "XP05:Prof:Mining", },
  {label = "Mists Skinning",          frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2560, locationID = 6666666, textInfo = "Mists Skinning\n - Open Profession After",           hideWhenCompleted = true, complete = { skillLineID = 2560 }, key = "XP05:Prof:Skinning", },
  {label = "Mists Tailoring",         frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2536, locationID = 6666666, textInfo = "Mists Tailoring\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2536 }, key = "XP05:Prof:Tailoring", },

--  04  CATACLYSM PROFESSIONS         If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Cata Alchemy",            frameID = "list1", professionSkillLineID = 171, missingProfessionSkillLineID = 2482, locationID = { 84, 85, }, textInfo = "Cata Alchemy\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2482 }, key = "XP04:Prof:Alchemy", },
  {label = "Cata Blacksmithing",      frameID = "list1", professionSkillLineID = 164, missingProfessionSkillLineID = 2474, locationID = { 84, 85, }, textInfo = "Cata Blacksmithing\n - Open Profession After",   hideWhenCompleted = true, complete = { skillLineID = 2474 }, key = "XP04:Prof:Blacksmithing", },
  {label = "Cata Cooking",            frameID = "list1", professionSkillLineID = 185, missingProfessionSkillLineID = 2545, locationID = { 84, 85, }, textInfo = "Cata Cooking\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2545 }, key = "XP04:Prof:Cooking", },
  {label = "Cata Enchanting",         frameID = "list1", professionSkillLineID = 333, missingProfessionSkillLineID = 2491, locationID = { 84, 85, }, textInfo = "Cata Enchanting\n - Open Profession After",      hideWhenCompleted = true, complete = { skillLineID = 2491 }, key = "XP04:Prof:Enchanting", },
  {label = "Cata Engineering",        frameID = "list1", professionSkillLineID = 202, missingProfessionSkillLineID = 2503, locationID = { 84, 85, }, textInfo = "Cata Engineering\n - Open Profession After",     hideWhenCompleted = true, complete = { skillLineID = 2503 }, key = "XP04:Prof:Engineering", },
  {label = "Cata Fishing",            frameID = "list1", professionSkillLineID = 356, missingProfessionSkillLineID = 2589, locationID = { 84, 85, }, textInfo = "Cata Fishing\n - Open Profession After",         hideWhenCompleted = true, complete = { skillLineID = 2589 }, key = "XP04:Prof:Fishing", },
  {label = "Cata Herbalism",          frameID = "list1", professionSkillLineID = 182, missingProfessionSkillLineID = 2553, locationID = { 84, 85, }, textInfo = "Cata Herbalism\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2553 }, key = "XP04:Prof:Herbalism", },
  {label = "Cata Inscription",        frameID = "list1", professionSkillLineID = 773, missingProfessionSkillLineID = 2511, locationID = { 84, 85, }, textInfo = "Cata Inscription\n - Open Profession After",     hideWhenCompleted = true, complete = { skillLineID = 2511 }, key = "XP04:Prof:Inscription", },
  {label = "Cata Jewelcrafting",      frameID = "list1", professionSkillLineID = 755, missingProfessionSkillLineID = 2521, locationID = { 84, 85, }, textInfo = "Cata Jewelcrafting\n - Open Profession After",   hideWhenCompleted = true, complete = { skillLineID = 2521 }, key = "XP04:Prof:Jewelcrafting", },
  {label = "Cata Leatherworking",     frameID = "list1", professionSkillLineID = 165, missingProfessionSkillLineID = 2529, locationID = { 84, 85, }, textInfo = "Cata Leatherworking\n - Open Profession After",  hideWhenCompleted = true, complete = { skillLineID = 2529 }, key = "XP04:Prof:Leatherworking", },
  {label = "Cata Mining",             frameID = "list1", professionSkillLineID = 186, missingProfessionSkillLineID = 2569, locationID = { 84, 85, }, textInfo = "Cata Mining\n - Open Profession After",          hideWhenCompleted = true, complete = { skillLineID = 2569 }, key = "XP04:Prof:Mining", },
  {label = "Cata Skinning",           frameID = "list1", professionSkillLineID = 393, missingProfessionSkillLineID = 2561, locationID = { 84, 85, }, textInfo = "Cata Skinning\n - Open Profession After",        hideWhenCompleted = true, complete = { skillLineID = 2561 }, key = "XP04:Prof:Skinning", },
  {label = "Cata Tailoring",          frameID = "list1", professionSkillLineID = 197, missingProfessionSkillLineID = 2537, locationID = { 84, 85, }, textInfo = "Cata Tailoring\n - Open Profession After",       hideWhenCompleted = true, complete = { skillLineID = 2537 }, key = "XP04:Prof:Tailoring", },

--  01  CLASSIC PROFESSIONS           If Not Clearing, Try Loading a Profession's Book After Learning                      /dump C_Map.GetBestMapForUnit("player")
  {label = "Classic Alchemy",         frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 171,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 171 }, key = "XP01:Prof:Alchemy", },
  {label = "Classic Blacksmithing",   frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 164,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 164 }, key = "XP01:Prof:Blacksmithing", },
  {label = "Classic Cooking",         frameID = "list1",                                   missingProfessionSkillLineID = 185,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 185 }, key = "XP01:Prof:Cooking", },
  {label = "Classic Enchanting",      frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 333,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 333 }, key = "XP01:Prof:Enchanting", },
  {label = "Classic Engineering",     frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 202,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 202 }, key = "XP01:Prof:Engineering", },
  {label = "Classic Fishing",         frameID = "list1",                                   missingProfessionSkillLineID = 356,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 356 }, key = "XP01:Prof:Fishing", },
  {label = "Classic Herbalism",       frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 182,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 182 }, key = "XP01:Prof:Herbalism", },
  {label = "Classic Inscription",     frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 773,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 773 }, key = "XP01:Prof:Inscription", },
  {label = "Classic Jewelcrafting",   frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 755,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 755 }, key = "XP01:Prof:Jewelcrafting", },
  {label = "Classic Leatherworking",  frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 165,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 165 }, key = "XP01:Prof:Leatherworking", },
  {label = "Classic Mining",          frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 186,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 186 }, key = "XP01:Prof:Mining", },
  {label = "Classic Skinning",        frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 393,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 393 }, key = "XP01:Prof:Skinning", },
  {label = "Classic Tailoring",       frameID = "list1", missingPrimaryProfessions = true, missingProfessionSkillLineID = 197,                                                                                    hideWhenCompleted = true, complete = { skillLineID = 197 }, key = "XP01:Prof:Tailoring", },

  {label = "Guild Cloak A1",          frameID = "bar1",  textInfo = "|cff1eff00Guild Cloak|r", faction = "alliance",       locationID = 84, showIf = { factionID = 1168, minStanding = 6 },                                                              complete = { any = { { itemIDs = { 63352 }, includeBank = true }, }, }, key = "rep:guild:alliance:cloak1", },
  {label = "Guild Cloak A2",          frameID = "bar1",  textInfo = "|cff1eff00Guild Cloak|r", faction = "alliance",       locationID = 84, showIf = { all = { { factionID = 1168, minStanding = 7 }, { itemIDs = { 63352 }, includeBank = true }, }, }, complete = { any = { { itemIDs = { 63206 }, includeBank = true }, }, }, key = "rep:guild:alliance:cloak2", },
  {label = "Guild Cloak A3",          frameID = "bar1",  textInfo = "|cff1eff00Guild Cloak|r", faction = "alliance",       locationID = 84, showIf = { all = { { factionID = 1168, minStanding = 8 }, { itemIDs = { 63206 }, includeBank = true }, }, }, complete = { any = { { itemIDs = { 65360 }, includeBank = true }, }, }, key = "rep:guild:alliance:cloak3", },
  {label = "Guild Cloak H1",          frameID = "bar1",  textInfo = "|cff1eff00Guild Cloak|r", faction = "horde",          locationID = 85, showIf = { factionID = 1168, minStanding = 6 },                                                              complete = { any = { { itemIDs = { 63353 }, includeBank = true }, }, }, key = "rep:guild:horde:cloak1",    },
  {label = "Guild Cloak H2",          frameID = "bar1",  textInfo = "|cff1eff00Guild Cloak|r", faction = "horde",          locationID = 85, showIf = { all = { { factionID = 1168, minStanding = 7 }, { itemIDs = { 63353 }, includeBank = true }, }, }, complete = { any = { { itemIDs = { 63207 }, includeBank = true }, }, }, key = "rep:guild:horde:cloak2",    },
  {label = "Guild Cloak H3",          frameID = "bar1",  textInfo = "|cff1eff00Guild Cloak|r", faction = "horde",          locationID = 85, showIf = { all = { { factionID = 1168, minStanding = 8 }, { itemIDs = { 63207 }, includeBank = true }, }, }, complete = { any = { { itemIDs = { 65274 }, includeBank = true }, }, }, key = "rep:guild:horde:cloak3",    },

--  /dump C_Map.GetBestMapForUnit("player") 
--{label = "Phaze Blasted Cata", textInfo = "|cffa335eeCATACLYSM PHAZED|r", locationID = 17, frameID = "list2", questID = 66560, showIf = { completedQuestID = 66560 }, key = "zone:blastedlands:cataclysm", },
{label = "Phaze Blasted WoD",  questInfo = "|cffa335eeWARLORDS PHAZED|r",  locationID = 17, frameID = "list2", questID = 66560, key = "zone:blastedlands:warlords", }



}

for i = 1, #bakedRules do
  local r = bakedRules[i]
  if type(r) == "table" then
    if r._expansionID == nil then r._expansionID = EXPANSION_ID end
    if r._expansionName == nil then r._expansionName = EXPANSION_NAME end
    if r.questXY == nil and tonumber(r.questID) and r.qXept == nil then r.qXept = "N" end
    if type(r.key) == "string" then
      r.key = r.key:gsub("^custom:", "db:")
    end
    ns.rules[#ns.rules + 1] = r
  end
end
